sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Wojtas059/lab8_WMaj -f Dockerfile.dev2 .

script:
  - docker run -e CI=true Wojtas059/lab8_WMaj npm run test
