sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t wojmaj/lab8:tagname -f Dockerfile.dev2 .

script:
  - docker run -e CI=true wojmaj/lab8:tagname npm run test
