sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Wojciech\ Maj(Wojtas059)/lab8_WMaj -f Dockerfile.dev2 .

script:
  - docker run -e CI=true Wojciech\ Maj(Wojtas059)/lab8_WMaj npm run test
