sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t "Wojciech Maj"/lab8_WMaj -f Dockerfile.dev2 .

script:
  - docker run -e CI=true "Wojciech Maj"/lab8_WMaj npm run test
