FROM node:alpine

WORKDIR '/app'
ENV NODE_OPTIONS=--openssl-legacy-provider
COPY --chown=node:node package.json .


RUN npm install

COPY --chown=node:node . .

USER node
CMD ["npm", "run", "start"]



